using System.Text.Json;
using MedicLaunchApi.Models.OpenAI;
using MedicLaunchApi.Models.QuestionDTOs;

namespace MedicLaunchApi.Services
{
  public class QuestionGenerationService : IQuestionGenerationService
  {
    private readonly OpenAIService openAIService;

    public QuestionGenerationService(OpenAIService openAIService)
    {
      this.openAIService = openAIService;
    }

    private async Task<List<ChatMessage>> GenerateChatPrompt(string conditions)
    {
      var messages = new List<ChatMessage>();

      var systemUserMessage = "Goal:\nI want a set of high-quality multiple-choice questions (MCQs) aimed at final-year medical students in the UK. These MCQs should assess clinical decision-making skills, patient management approaches, and core medical knowledge in an integrated manner, combining clinical scenarios with relevant basic sciences. Each question should be challenging and useful for assessing readiness for practice.\n\nReturn Format:\nProvide each MCQ structured clearly with the following elements:\n- A concise clinical vignette outlining a realistic patient scenario.\n- Clearly worded question stem.\n- Five answer options labelled (a) through (e), ensuring there is only one correct and unambiguously best answer per question. The other four distractors must be plausible but incorrect.\n- Clearly indicated correct answer.\n- A short, evidence-based explanation accompanying the correct answer, referencing current guidelines and best practices applicable within the UK healthcare system.\n\nYou MUST ENSURE that each response adheres STRICTLY to the following JSON schema:\n{\n  \"questionText\": \"string\",\n  \"options\": [\n    {\n      \"letter\": \"string (max length: 1)\",\n      \"text\": \"string\"\n    }\n  ],\n  \"correctAnswerLetter\": \"string (max length: 1)\",\n  \"explanation\": \"string\"\n}\nNote that the \"questionText\" and \"explanation\" fields are strings of HTML.\n\nWarnings:\n- Ensure that vignettes, stems, and answer choices avoid ambiguity. Do not write questions that are misleading or inaccurate.\n- Do not include outdated information; all questions and answers must reflect current, evidence-based guidelines from NICE CKS and uk guidelines.\n- Ensure integration with basic sciences is clear and relevant; do not choose overly specialised or obscure basic science information.\n- In the explanation, do not refer to answer choices by letter e.g. \"Answer B is incorrect because...\". Instead, refer to them by the answer text e.g. \"Cystic fibrosis is incorrect because...\".\n- Ensure that answer options are plain text strings, without any HTML formatting.\n\nContext:\nThese MCQs are intended to help final-year medical students preparing for their final exams and clinical practice in the UK. Students will have familiarity with common UK guidelines (NICE, SIGN, GMC recommendations) and will be preparing to enter medical practice within the NHS soon. Coverage should focus on high-yield topics which are common but also cover the areas outlined, clinically meaningful, and critical for safe patient care. The questions are designed to assess the student's ability to apply theoretical knowledge and guidelines to real-world clinical situations effectively.";
      messages.Add(new ChatMessage { Role = "user", Content = [new ChatContent { Text = systemUserMessage }] });
      var example1UserMessage = "Turn the following into an MCQ: Colorectal Cancer - older patient, change in bowel habits, iron-deficiency anemia, rectal bleeding, colonoscopy reveal a mass. Diagnosis?";
      messages.Add(new ChatMessage { Role = "user", Content = [new ChatContent { Text = example1UserMessage }] });
      var example1AssistantMessage = "{\n  \"questionText\": \"<p>A 68-year-old man presents to his GP with a three month history of a change in bowel habits, including alternating constipation and diarrhoea. He has also noticed occasional rectal bleeding and reports feeling increasingly fatigued. Blood tests reveal iron-deficiency anaemia and examination shows a small haemorrhoid. </p><p></p><p><strong>What is the single most likely diagnosis?</strong></p>\",\n  \"options\": [\n    {\n      \"letter\": \"A\",\n      \"text\": \"Colorectal Cancer\"\n    },\n    {\n      \"letter\": \"B\",\n      \"text\": \"Diverticular disease\"\n    },\n    {\n      \"letter\": \"C\",\n      \"text\": \"Haemorrhoids\"\n    },\n    {\n      \"letter\": \"D\",\n      \"text\": \"Ischaemic Colitis\"\n    },\n    {\n      \"letter\": \"E\",\n      \"text\": \"Ulcerative Colitis\"\n    }\n  ],\n  \"correctAnswerLetter\": \"A\",\n  \"explanation\": \"<p>The single most likely diagnosis is colorectal cancer, as the patient presents with classic red-flag symptoms, including a persistent change in bowel habits, iron-deficiency anaemia, fatigue, and rectal bleeding. While haemorrhoids are noted on examination, they do not account for systemic symptoms like anaemia or changes in bowel habits and should not be considered the sole cause of rectal bleeding in this context, particularly in an older patient.</p><p></p><p>Haemorrhoids typically cause bright red bleeding with defecation but do not explain iron-deficiency anaemia or altered bowel habits. Diverticular disease can cause rectal bleeding and bowel habit changes but is less likely to cause anaemia or fatigue without significant complications like chronic blood loss. Ulcerative colitis may present with rectal bleeding and anaemia, but it typically includes chronic abdominal pain, weight loss, or systemic symptoms like fever. Ischaemic colitis usually presents with acute abdominal pain and bloody diarrhoea, not a chronic change in bowel habits or anaemia.</p>\"\n}";
      messages.Add(new ChatMessage { Role = "assistant", Content = [new ChatContent { Text = example1AssistantMessage }] });
      var example2UserMessage = "Turn the following into an MCQ: Acute Myocarditis - viral infection → develops cardiac symptoms - whats the dx?";
      messages.Add(new ChatMessage { Role = "user", Content = [new ChatContent { Text = example2UserMessage }] });
      var example2AssistantMessage = "{\n  \"questionText\": \"<p>A 24-year-old male presents to the Emergency Department with a 5-day history of worsening fatigue, shortness of breath on exertion, and chest discomfort. He reports having a \\\"cold\\\" two weeks ago with symptoms of a sore throat, runny nose, and mild fever, which resolved on its own. Observations include a pulse of 110/min, blood pressure 100/60 mmHg. An ECG shows sinus tachycardia with non-specific ST-segment changes. A troponin test is positive, and a bedside echocardiogram reveals a mildly reduced ejection fraction.</p><p></p><p><strong>What is the most likely diagnosis?</strong></p>\",\n  \"options\": [\n    {\n      \"letter\": \"A\",\n      \"text\": \"Acute coronary syndrome\"\n    },\n    {\n      \"letter\": \"B\",\n      \"text\": \"Acute myocarditis\"\n    },\n    {\n      \"letter\": \"C\",\n      \"text\": \"Pericarditis\"\n    },\n    {\n      \"letter\": \"E\",\n      \"text\": \"Viral pleuritis \"\n    },\n    {\n      \"letter\": \"D\",\n      \"text\": \"Pulmonary embolism\"\n    }\n  ],\n  \"correctAnswerLetter\": \"B\",\n  \"explanation\": \"<p>Acute myocarditis is the most likely diagnosis because it often follows a viral infection and presents with symptoms of heart failure or chest pain. The history of a recent \\\"cold,\\\" combined with the cardiac symptoms, positive troponin, and reduced ejection fraction on echocardiogram, all point towards myocarditis as the underlying cause.</p><p></p><p>Acute coronary syndrome is less likely due to the patient’s age, lack of risk factors, and viral history. Pulmonary embolism usually presents with pleuritic chest pain and shortness of breath but does not account for reduced ejection fraction or viral illness. Pericarditis may cause chest pain and ECG changes but not typically a reduced ejection fraction. Viral pleuritis could cause chest pain but doesn\'t explain the positive troponin or reduced ejection fraction.</p>\"\n}";
      messages.Add(new ChatMessage { Role = "assistant", Content = [new ChatContent { Text = example2AssistantMessage }] });
      var example3UserMessage = "Turn the following into an MCQ: Tuberculosis - visited Pakistan, night sweats, hemoptysis, apical crackles. Initial step in management?";
      messages.Add(new ChatMessage { Role = "user", Content = [new ChatContent { Text = example3UserMessage }] });
      var example3AssistantMessage = "{\n  \"questionText\": \"<p>A 32-year-old man presents to the GP with a 3-week history of night sweats, persistent cough, and haemoptysis. He has recently returned from a visit to Pakistan. On examination, there are apical crackles in his lungs and a sweaty t-shirt.&nbsp;</p><p></p><p><strong><span style=\\\"color: inherit; font-family: inherit; font-size: inherit\\\">What is the most appropriate initial step in management?</span></strong></p>\",\n  \"options\": [\n    {\n      \"letter\": \"A\",\n      \"text\": \"Arrange for a Mantoux test\"\n    },\n    {\n      \"letter\": \"B\",\n      \"text\": \"Isolate the patient and obtain sputum samples for acid-fast bacilli testing \"\n    },\n    {\n      \"letter\": \"C\",\n      \"text\": \"Order a chest X-ray\"\n    },\n    {\n      \"letter\": \"D\",\n      \"text\": \"Refer for bronchoscopy and biopsy\"\n    },\n    {\n      \"letter\": \"E\",\n      \"text\": \"Start empirical anti-tuberculosis therapy\"\n    }\n  ],\n  \"correctAnswerLetter\": \"B\",\n  \"explanation\": \"<p>The patient’s history of travel to an area with a high prevalence of tuberculosis, combined with his symptoms of night sweats, haemoptysis, and apical crackles, strongly suggests pulmonary tuberculosis (TB). The most appropriate initial step in management is to isolate the patient and obtain sputum samples for acid-fast bacilli (AFB) testing. Isolation is critical to prevent the spread of TB, and obtaining sputum samples is essential for confirming the diagnosis through microbiological testing.&nbsp;</p><p></p><p>Starting empirical anti-tuberculosis therapy without confirmation is premature; a chest X-ray should follow patient isolation and sputum sampling; the Mantoux test is less useful for active TB; and bronchoscopy is reserved for inconclusive sputum results or non-pulmonary TB suspicion.</p>\"\n}";
      messages.Add(new ChatMessage { Role = "assistant", Content = [new ChatContent { Text = example3AssistantMessage }] });

      var content = $"Turn the following into an MCQ: {conditions}";
      messages.Add(new ChatMessage { Role = "user", Content = [new ChatContent { Text = content }] });

      return messages;
    }

    public async Task<QuestionTextAndExplanation> GenerateQuestionTextAndExplanationAsync(string content)
    {
      var messages = await GenerateChatPrompt(content);

      var response = await openAIService.GenerateChatCompletion(messages);

      JsonSerializerOptions jsonOptions = new()
      {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
      };

      return JsonSerializer.Deserialize<QuestionTextAndExplanation>(response, jsonOptions);
    }
  }
}